import {
  LocalService,
  RealmSummary,
  RegionSummary,
} from '@clients/devops-ui-service-api-client';

export const mockRegions: RegionSummary[] = [
  {
    realm: 'oc1',
    realmType: 'commercial',
    isDisconnected: false,
    ads: [1],
    pops: [1],
    publicRegionName: 'eu-paris-1',
    airportCode: 'cdg',
    internalName: 'eu-paris-1',
    vibeRegion: 'eu-frankfurt-1',
    publicDomainName: 'oraclecloud.com',
    iaasDomainName: 'oracleiaas.com',
    ociPublicDomainName: 'oci.oraclecloud.com',
    ociIaasDomainName: 'oci.oracleiaas.com',
    state: 'Building',
  },
  {
    realm: 'oc11',
    realmType: 'government',
    isDisconnected: true,
    ads: [1],
    pops: [],
    publicRegionName: 'us-gov-sterling-3',
    airportCode: 'hef',
    internalName: 'us-gov-sterling-3',
    vibeRegion: 'us-ashburn-1',
    publicDomainName: 'oraclecloud.smil.mil',
    iaasDomainName: 'oraclerealm.smil.mil',
    ociPublicDomainName: 'oci.oraclecloud.smil.mil',
    ociIaasDomainName: 'oci.oraclerealm.smil.mil',
    state: 'Building',
  },
  {
    realm: 'oc1',
    realmType: 'commercial',
    isDisconnected: false,
    ads: [1],
    pops: [],
    publicRegionName: 'mx-queretaro-1',
    airportCode: 'qro',
    internalName: 'mx-queretaro-1',
    vibeRegion: 'us-sanjose-1',
    publicDomainName: 'oraclecloud.com',
    iaasDomainName: 'oracleiaas.com',
    ociPublicDomainName: 'oci.oraclecloud.com',
    ociIaasDomainName: 'oci.oracleiaas.com',
    state: 'Building',
  },
  {
    realm: 'oc11',
    realmType: 'government',
    isDisconnected: true,
    ads: [1],
    pops: [],
    publicRegionName: 'us-gov-fortworth-3',
    airportCode: 'dal',
    internalName: 'us-gov-fortworth-3',
    vibeRegion: 'us-phoenix-1',
    publicDomainName: 'oraclecloud.smil.mil',
    iaasDomainName: 'oraclerealm.smil.mil',
    ociPublicDomainName: 'oci.oraclecloud.smil.mil',
    ociIaasDomainName: 'oci.oraclerealm.smil.mil',
    state: 'Building',
  },
  {
    realm: 'oc11',
    realmType: 'government',
    isDisconnected: true,
    ads: [1],
    pops: [],
    publicRegionName: 'us-gov-phoenix-3',
    airportCode: 'gyr',
    internalName: 'us-gov-phoenix-3',
    vibeRegion: 'us-phoenix-1',
    publicDomainName: 'oraclecloud.smil.mil',
    iaasDomainName: 'oraclerealm.smil.mil',
    ociPublicDomainName: 'oci.oraclecloud.smil.mil',
    ociIaasDomainName: 'oci.oraclerealm.smil.mil',
    state: 'Building',
  },
  {
    realm: 'oc1',
    realmType: 'government',
    isDisconnected: true,
    ads: [1],
    pops: [],
    publicRegionName: 'sol-saturn-1',
    airportCode: 'gyr',
    internalName: 'sol-saturn-1',
    publicDomainName: 'oraclecloud.smil.mil',
    iaasDomainName: 'oraclerealm.smil.mil',
    ociPublicDomainName: 'oci.oraclecloud.smil.mil',
    ociIaasDomainName: 'oci.oraclerealm.smil.mil',
    state: 'Building',
  },
  {
    realm: 'oc1',
    realmType: 'commercial',
    isDisconnected: true,
    ads: [1],
    pops: [],
    publicRegionName: 'eu-madrid-1',
    airportCode: 'gyr',
    internalName: 'eu-madrid-1',
    publicDomainName: 'oraclecloud.smil.mil',
    iaasDomainName: 'oraclerealm.smil.mil',
    ociPublicDomainName: 'oci.oraclecloud.smil.mil',
    ociIaasDomainName: 'oci.oraclerealm.smil.mil',
    state: 'Production',
  },
  {
    realm: 'oc1',
    realmType: 'commercial',
    isDisconnected: false,
    ads: [1, 2, 3],
    pops: [1, 2],
    marketplace: 'commercial',
    publicRegionName: 'us-ashburn-1',
    airportCode: 'iad',
    internalName: 'us-ashburn-1',
    publicDomainName: 'oraclecloud.com',
    iaasDomainName: 'oracleiaas.com',
    ociPublicDomainName: 'oci.oraclecloud.com',
    ociIaasDomainName: 'oci.oracleiaas.com',
    state: 'Production',
  },
  {
    realm: 'oc1',
    realmType: 'commercial',
    isDisconnected: false,
    ads: [1, 2, 3],
    pops: [],
    marketplace: 'commercial',
    publicRegionName: 'us-phoenix-1',
    airportCode: 'phx',
    internalName: 'r2',
    publicDomainName: 'oraclecloud.com',
    iaasDomainName: 'oracleiaas.com',
    ociPublicDomainName: 'oci.oraclecloud.com',
    ociIaasDomainName: 'oci.oracleiaas.com',
    state: 'Production',
  },
];

export const unresolvableDns =
  'vibe-gone.eu-paris-1.vibe.us-ashburn-1.oracleiaas.com';

export const unresolvableDnsService = 'service-with-unresolvable-vibe-dns';

export const mockLocalServices: LocalService[] = [
  // FIXME: signingTranslation.test.ts is tightly-coupled to order of services
  {
    realm: 'oc1',
    region: 'us-ashburn-1',
    ad: 1,
    serviceName: 'splat',
    apiPath: '/api/splat/us-ashburn-1',
    dnsName: 'splat-api-v2.us-ashburn-1.oci.oraclecloud.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
    regionState: 'Production',
  },
  {
    realm: 'oc1',
    region: 'sol-saturn-1',
    ad: 1,
    serviceName: 'canary-sol-saturn-1-backend-41',
    apiPath: '/api/test/us-ashburn-1',
    dnsName:
      'backend.test-service-regional.sol-saturn-1.vibe.ca-montreal-1.oci.oracleiaas.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
  },
  {
    realm: 'oc1',
    region: 'sol-saturn-1',
    ad: 1,
    serviceName: 'canary-sol-saturn-1-backend-4000',
    apiPath: '/api/test/us-ashburn-1',
    dnsName:
      'backend.test-service-regional-4000.sol-saturn-1.vibe.ca-montreal-1.oci.oracleiaas.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: ['foo'],
  },
  {
    realm: 'oc1',
    region: 'us-ashburn-1',
    ad: 1,
    serviceName: 'canary-sol-saturn-1-backend-4000',
    apiPath: '/api/test/us-ashburn-1',
    dnsName:
      'backend.test-service-regional-4000.sol-saturn-1.vibe.us-ashburn-1.oci.oracleiaas.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
    regionState: 'Production',
  },
  {
    realm: 'oc1',
    region: 'eu-madrid-1',
    ad: 1,
    serviceName: 'ibex_control-eu-madrid-1-backend-257',
    apiPath: '/api/ibex/us-ashburn-1',
    dnsName: 'controlplane.logging.ad1.eu-madrid-1.oci.oracleiaas.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
    regionState: 'Production',
  },
  {
    realm: 'oc1',
    ad: 1,
    serviceName: 'ibex_control-us-gov-manassas-1-backend-283',
    apiPath: '/api/ibex/us-ashburn-1',
    dnsName:
      'controlplane.logging.ad1.us-gov-manassas-1.oci.oracledodrealm.ic.gov',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
  },
  {
    realm: 'oc1',
    region: 'us-ashburn-1',
    ad: 1,
    serviceName: 'account-backend-1',
    apiPath: '/api/bling/us-ashburn-1',
    dnsName: 'bling.us-az-ashburn-1.oracleiaas.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
    regionState: 'Production',
  },
  {
    realm: 'oc1',
    region: 'us-phoenix-1',
    ad: 1,
    serviceName: 'account-backend-1',
    apiPath: '/api/bling/us-phoenix-1',
    dnsName: 'bling.us-az-phoenix-1.oracleiaas.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
    regionState: 'Production',
  },
  {
    realm: 'oc1',
    region: 'us-ashburn-1',
    ad: 2,
    serviceName: 'account-backend-1',
    apiPath: '/api/bling/us-ashburn-1',
    dnsName: 'bling.us-az-unknown-1.oracleiaas.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
    regionState: 'Production',
  },
  {
    realm: 'oc1',
    region: 'eu-paris-1',
    ad: 1,
    serviceName: 'foobar-service-4-u',
    dnsName: 'foobar.eu-paris-1.oracleiaas.com',
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
    regionState: 'Building',
    apiPath: '/api/foobar/eu-paris-1',
  },
  {
    realm: 'oc1',
    region: 'eu-paris-1',
    ad: 1,
    serviceName: unresolvableDnsService,
    dnsName: 'vibe-gone.eu-paris-1.oracleiaas.com',
    vibeDnsName: unresolvableDns,
    port: 443,
    sni: false,
    http: false,
    missingCapabilities: [],
    regionState: 'Building',
    apiPath: '/api/foobar/eu-paris-1',
  },
];

export const mockRealms: RealmSummary[] = [
  {
    name: 'region1',
    isTest: false,
    isDisconnected: false,
    firstRegionSummary: {
      realm: 'region1',
      isDisconnected: false,
      ads: [1, 2],
      pops: [],
      publicRegionName: 'us-seattle-1',
      airportCode: 'sea',
      internalName: 'r1',
      publicDomainName: 'oraclecloud.com',
      iaasDomainName: 'oracleiaas.com',
      ociPublicDomainName: 'oci.oraclecloud.com',
      ociIaasDomainName: 'oci.oracleiaas.com',
      state: 'Production',
    },
    regions: ['us-seattle-1'],
  },
  {
    name: 'oc1',
    isTest: false,
    isDisconnected: false,
    firstRegionSummary: {
      realm: 'oc1',
      isDisconnected: false,
      ads: [1, 2, 3],
      pops: [],
      publicRegionName: 'us-phoenix-1',
      airportCode: 'phx',
      internalName: 'r2',
      publicDomainName: 'oraclecloud.com',
      iaasDomainName: 'oracleiaas.com',
      ociPublicDomainName: 'oci.oraclecloud.com',
      ociIaasDomainName: 'oci.oracleiaas.com',
      state: 'Production',
    },
    regions: ['us-phoenix-1', 'us-ashburn-1', 'uk-london-1'],
  },
  {
    name: 'oc2',
    isTest: false,
    isDisconnected: false,
    firstRegionSummary: {
      realm: 'oc2',
      isDisconnected: false,
      ads: [1],
      pops: [1],
      publicRegionName: 'us-langley-1',
      airportCode: 'lfi',
      internalName: 'us-langley-1',
      publicDomainName: 'oraclegovcloud.com',
      iaasDomainName: 'oraclegoviaas.com',
      ociPublicDomainName: 'oci.oraclegovcloud.com',
      ociIaasDomainName: 'oci.oraclegoviaas.com',
      state: 'Production',
    },
    regions: ['us-langley-1', 'us-luke-1'],
  },
  {
    name: 'oc3',
    isTest: false,
    isDisconnected: false,
    firstRegionSummary: {
      realm: 'oc3',
      isDisconnected: false,
      ads: [1],
      pops: [1],
      publicRegionName: 'us-gov-ashburn-1',
      airportCode: 'ric',
      internalName: 'us-gov-ashburn-1',
      publicDomainName: 'oraclegovcloud.com',
      iaasDomainName: 'oraclegoviaas.com',
      ociPublicDomainName: 'oci.oraclegovcloud.com',
      ociIaasDomainName: 'oci.oraclegoviaas.com',
      state: 'Production',
    },
    regions: ['us-gov-phoenix-1', 'us-gov-ashburn-1', 'us-gov-chicago-1'],
  },
  {
    name: 'oc4',
    isDisconnected: false,
    isTest: false,
    firstRegionSummary: {
      realm: 'oc4',
      isDisconnected: false,
      ads: [1],
      pops: [],
      publicRegionName: 'uk-gov-london-1',
      airportCode: 'ltn',
      internalName: 'uk-gov-london-1',
      publicDomainName: 'oraclegovcloud.uk',
      iaasDomainName: 'oraclegoviaas.uk',
      ociPublicDomainName: 'oci.oraclegovcloud.uk',
      ociIaasDomainName: 'oci.oraclegoviaas.uk',
      state: 'Production',
    },
    regions: ['uk-gov-london-1', 'uk-gov-cardiff-1'],
  },
  {
    name: 'oc11',
    realmType: 'government',
    isDisconnected: true,
    isTest: false,
    firstRegionSummary: {
      realm: 'oc11',
      realmType: 'government',
      isDisconnected: true,
      ads: [1],
      pops: [],
      publicRegionName: 'us-gov-fortworth-3',
      airportCode: 'dal',
      internalName: 'us-gov-fortworth-3',
      vibeRegion: 'us-phoenix-1',
      publicDomainName: 'oraclecloud.smil.mil',
      iaasDomainName: 'oraclerealm.smil.mil',
      ociPublicDomainName: 'oci.oraclecloud.smil.mil',
      ociIaasDomainName: 'oci.oraclerealm.smil.mil',
      state: 'Building',
    },
    regions: ['us-gov-fortworth-3', 'us-gov-phoenix-3', 'us-gov-sterling-3'],
  },
  {
    name: 'oc6',
    realmType: 'government',
    isDisconnected: true,
    isTest: false,
    firstRegionSummary: {
      realm: 'oc6',
      realmType: 'government',
      isDisconnected: true,
      ads: [1],
      pops: [],
      publicRegionName: 'us-gov-fortworth-1',
      airportCode: 'ftw',
      internalName: 'us-gov-fortworth-1',
      vibeRegion: 'us-phoenix-1',
      publicDomainName: 'oraclecloud.ic.gov',
      iaasDomainName: 'oraclerealm.ic.gov',
      ociPublicDomainName: 'oci.oraclecloud.ic.gov',
      ociIaasDomainName: 'oci.oraclerealm.ic.gov',
      state: 'Production',
    },
    regions: ['us-gov-fortworth-1', 'us-gov-sterling-2'],
  },
  {
    name: 'oc5',
    realmType: 'government',
    isDisconnected: true,
    isTest: false,
    firstRegionSummary: {
      realm: 'oc5',
      realmType: 'government',
      isDisconnected: true,
      ads: [1],
      pops: [],
      publicRegionName: 'us-tacoma-1',
      airportCode: 'tiw',
      internalName: 'us-tacoma-1',
      vibeRegion: 'us-phoenix-1',
      publicDomainName: 'oraclecloud5.com',
      iaasDomainName: 'oraclerealm5.com',
      ociPublicDomainName: 'oci.oraclecloud5.com',
      ociIaasDomainName: 'oci.oraclerealm5.com',
      state: 'Production',
    },
    regions: ['us-tacoma-1'],
  },
  {
    name: 'oc19',
    realmType: 'commercial',
    isDisconnected: false,
    isSovereign: true,
    isTest: false,
    firstRegionSummary: {
      realm: 'oc19',
      realmType: 'commercial',
      isDisconnected: false,
      isSovereign: true,
      ads: [1],
      pops: [],
      publicRegionName: 'eu-madrid-2',
      airportCode: 'vll',
      internalName: 'eu-madrid-2',
      vibeRegion: 'eu-madrid-1',
      publicDomainName: 'oraclecloud.eu',
      iaasDomainName: 'oraclerealm.eu',
      ociPublicDomainName: 'oci.oraclecloud.eu',
      ociIaasDomainName: 'oci.oraclerealm.eu',
      state: 'Production',
    },
    regions: ['eu-madrid-2', 'eu-frankfurt-2'],
  },
];
