"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Block = exports.Footer = void 0;
var flatbuffers_1 = require("flatbuffers");
var NS13596923344997147894 = require("./Schema");
/**
 * ----------------------------------------------------------------------
 * Arrow File metadata
 *
 *
 * @constructor
 */
var Footer = /** @class */ (function () {
    function Footer() {
        this.bb = null;
        this.bb_pos = 0;
    }
    /**
     * @param number i
     * @param flatbuffers.ByteBuffer bb
     * @returns Footer
     */
    Footer.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * @param flatbuffers.ByteBuffer bb
     * @param Footer= obj
     * @returns Footer
     */
    Footer.getRootAsFooter = function (bb, obj) {
        return (obj || new Footer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    /**
     * @param flatbuffers.ByteBuffer bb
     * @param Footer= obj
     * @returns Footer
     */
    Footer.getSizePrefixedRootAsFooter = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers_1.flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Footer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    /**
     * @returns MetadataVersion
     */
    Footer.prototype.version = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? /**  */ (this.bb.readInt16(this.bb_pos + offset)) : NS13596923344997147894.MetadataVersion.V1;
    };
    /**
     * @param Schema= obj
     * @returns Schema|null
     */
    Footer.prototype.schema = function (obj) {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? (obj || new NS13596923344997147894.Schema()).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
    };
    /**
     * @param number index
     * @param Block= obj
     * @returns Block
     */
    Footer.prototype.dictionaries = function (index, obj) {
        var offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? (obj || new Block()).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
    };
    /**
     * @returns number
     */
    Footer.prototype.dictionariesLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    /**
     * @param number index
     * @param Block= obj
     * @returns Block
     */
    Footer.prototype.recordBatches = function (index, obj) {
        var offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? (obj || new Block()).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
    };
    /**
     * @returns number
     */
    Footer.prototype.recordBatchesLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    /**
     * User-defined metadata
     *
     * @param number index
     * @param KeyValue= obj
     * @returns KeyValue
     */
    Footer.prototype.customMetadata = function (index, obj) {
        var offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? (obj || new NS13596923344997147894.KeyValue()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    };
    /**
     * @returns number
     */
    Footer.prototype.customMetadataLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    /**
     * @param flatbuffers.Builder builder
     */
    Footer.startFooter = function (builder) {
        builder.startObject(5);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param MetadataVersion version
     */
    Footer.addVersion = function (builder, version) {
        builder.addFieldInt16(0, version, NS13596923344997147894.MetadataVersion.V1);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Offset schemaOffset
     */
    Footer.addSchema = function (builder, schemaOffset) {
        builder.addFieldOffset(1, schemaOffset, 0);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Offset dictionariesOffset
     */
    Footer.addDictionaries = function (builder, dictionariesOffset) {
        builder.addFieldOffset(2, dictionariesOffset, 0);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param number numElems
     */
    Footer.startDictionariesVector = function (builder, numElems) {
        builder.startVector(24, numElems, 8);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Offset recordBatchesOffset
     */
    Footer.addRecordBatches = function (builder, recordBatchesOffset) {
        builder.addFieldOffset(3, recordBatchesOffset, 0);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param number numElems
     */
    Footer.startRecordBatchesVector = function (builder, numElems) {
        builder.startVector(24, numElems, 8);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Offset customMetadataOffset
     */
    Footer.addCustomMetadata = function (builder, customMetadataOffset) {
        builder.addFieldOffset(4, customMetadataOffset, 0);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param Array.<flatbuffers.Offset> data
     * @returns flatbuffers.Offset
     */
    Footer.createCustomMetadataVector = function (builder, data) {
        builder.startVector(4, data.length, 4);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    };
    /**
     * @param flatbuffers.Builder builder
     * @param number numElems
     */
    Footer.startCustomMetadataVector = function (builder, numElems) {
        builder.startVector(4, numElems, 4);
    };
    /**
     * @param flatbuffers.Builder builder
     * @returns flatbuffers.Offset
     */
    Footer.endFooter = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Offset offset
     */
    Footer.finishFooterBuffer = function (builder, offset) {
        builder.finish(offset);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Offset offset
     */
    Footer.finishSizePrefixedFooterBuffer = function (builder, offset) {
        builder.finish(offset, undefined, true);
    };
    Footer.createFooter = function (builder, version, schemaOffset, dictionariesOffset, recordBatchesOffset, customMetadataOffset) {
        Footer.startFooter(builder);
        Footer.addVersion(builder, version);
        Footer.addSchema(builder, schemaOffset);
        Footer.addDictionaries(builder, dictionariesOffset);
        Footer.addRecordBatches(builder, recordBatchesOffset);
        Footer.addCustomMetadata(builder, customMetadataOffset);
        return Footer.endFooter(builder);
    };
    return Footer;
}());
exports.Footer = Footer;
/**
 * @constructor
 */
var Block = /** @class */ (function () {
    function Block() {
        this.bb = null;
        this.bb_pos = 0;
    }
    /**
     * @param number i
     * @param flatbuffers.ByteBuffer bb
     * @returns Block
     */
    Block.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * Index to the start of the RecordBlock (note this is past the Message header)
     *
     * @returns flatbuffers.Long
     */
    Block.prototype.offset = function () {
        return this.bb.readInt64(this.bb_pos);
    };
    /**
     * Length of the metadata
     *
     * @returns number
     */
    Block.prototype.metaDataLength = function () {
        return this.bb.readInt32(this.bb_pos + 8);
    };
    /**
     * Length of the data (this is aligned so there can be a gap between this and
     * the metadata).
     *
     * @returns flatbuffers.Long
     */
    Block.prototype.bodyLength = function () {
        return this.bb.readInt64(this.bb_pos + 16);
    };
    /**
     * @param flatbuffers.Builder builder
     * @param flatbuffers.Long offset
     * @param number metaDataLength
     * @param flatbuffers.Long bodyLength
     * @returns flatbuffers.Offset
     */
    Block.createBlock = function (builder, offset, metaDataLength, bodyLength) {
        builder.prep(8, 24);
        builder.writeInt64(bodyLength);
        builder.pad(4);
        builder.writeInt32(metaDataLength);
        builder.writeInt64(offset);
        return builder.offset();
    };
    return Block;
}());
exports.Block = Block;

//# sourceMappingURL=File.js.map
